import { motion } from 'framer-motion'
import { FiCheck, FiAlertCircle, FiTarget, FiTool, FiEdit, FiStar, FiDownload, FiRefreshCw, FiAward, FiTrendingUp } from 'react-icons/fi'
import { FaChartLine, FaRegLightbulb } from 'react-icons/fa'
import ScoreCircle from './ScoreCircle'

const ResultsDisplay = ({ feedback, onNewReview }) => {
  const sections = [
    {
      id: 'summary',
      title: 'Overall Summary',
      icon: FiStar,
      color: 'from-emerald-500 to-teal-500',
      content: feedback.summary
    },
    {
      id: 'strengths',
      title: 'Strengths',
      icon: FiCheck,
      color: 'from-emerald-500 to-teal-500',
      content: feedback.strengths,
      isList: true
    },
    {
      id: 'weaknesses',
      title: 'Areas for Improvement',
      icon: FiAlertCircle,
      color: 'from-amber-500 to-orange-500',
      content: feedback.weaknesses,
      isList: true
    },
    {
      id: 'missingSkills',
      title: 'Missing Skills',
      icon: FiTarget,
      color: 'from-violet-500 to-purple-500',
      content: feedback.missingSkills,
      isList: true
    },
    {
      id: 'atsOptimization',
      title: 'ATS Optimization',
      icon: FiTool,
      color: 'from-blue-500 to-cyan-500',
      content: feedback.atsOptimization,
      isList: true
    },
    {
      id: 'grammarImprovements',
      title: 'Grammar & Clarity',
      icon: FiEdit,
      color: 'from-rose-500 to-pink-500',
      content: feedback.grammarImprovements,
      isList: true
    }
  ]

  const getColorClasses = (color) => {
    const colors = {
      'from-emerald-500 to-teal-500': 'bg-linear-to-r from-emerald-500/10 to-teal-500/10 border-emerald-500/20 text-emerald-300',
      'from-amber-500 to-orange-500': 'bg-linear-to-r from-amber-500/10 to-orange-500/10 border-amber-500/20 text-amber-300',
      'from-violet-500 to-purple-500': 'bg-linear-to-r from-violet-500/10 to-purple-500/10 border-violet-500/20 text-violet-300',
      'from-blue-500 to-cyan-500': 'bg-linear-to-r from-blue-500/10 to-cyan-500/10 border-blue-500/20 text-blue-300',
      'from-rose-500 to-pink-500': 'bg-linear-to-r from-rose-500/10 to-pink-500/10 border-rose-500/20 text-rose-300'
    }
    return colors[color] || colors['from-emerald-500 to-teal-500'];
  }

  const getDotColor = (color) => {
    const colors = {
      'from-emerald-500 to-teal-500': 'bg-emerald-400',
      'from-amber-500 to-orange-500': 'bg-amber-400',
      'from-violet-500 to-purple-500': 'bg-violet-400',
      'from-blue-500 to-cyan-500': 'bg-blue-400',
      'from-rose-500 to-pink-500': 'bg-rose-400'
    }
    return colors[color] || colors['from-emerald-500 to-teal-500'];
  }

  const downloadReport = () => {
    const reportContent = `
AI Resume Review Report
=======================

Overall Score: ${feedback.score}/100

SUMMARY:
${feedback.summary}

STRENGTHS:
${feedback.strengths.map((s, i) => `${i + 1}. ${s}`).join('\n')}

AREAS FOR IMPROVEMENT:
${feedback.weaknesses.map((w, i) => `${i + 1}. ${w}`).join('\n')}

MISSING SKILLS:
${feedback.missingSkills.map((s, i) => `${i + 1}. ${s}`).join('\n')}

ATS OPTIMIZATION:
${feedback.atsOptimization.map((a, i) => `${i + 1}. ${a}`).join('\n')}

GRAMMAR & CLARITY:
${feedback.grammarImprovements.map((g, i) => `${i + 1}. ${g}`).join('\n')}

RECOMMENDATIONS:
${feedback.recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}

Generated by AI Resume Reviewer
${new Date().toLocaleDateString()}
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'resume-analysis-report.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  return (
    <div className="relative">
      {/* Background Effects */}
      <div className="absolute inset-0 -z-10">
        <div className="absolute top-0 left-0 w-64 h-64 bg-emerald-500/5 rounded-full blur-3xl"></div>
        <div className="absolute bottom-0 right-0 w-64 h-64 bg-violet-500/5 rounded-full blur-3xl"></div>
      </div>

      {/* Header Card */}
      <motion.div 
        className="glass-card p-8 mb-8 hover:shadow-2xl hover:shadow-emerald-500/10 transition-all duration-500"
        initial={{ y: -20, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
      >
        <div className="flex flex-col lg:flex-row items-center justify-between gap-8">
          <div className="flex-1">
            <div className="flex items-center gap-3 mb-6">
              <div className="p-2 rounded-lg bg-linear-to-r from-emerald-500/10 to-teal-500/10 border border-emerald-500/20">
                <FaChartLine className="w-6 h-6 text-emerald-400" />
              </div>
              <div>
                <h2 className="text-3xl font-bold text-white">Resume Analysis Complete</h2>
                <p className="text-zinc-400 mt-1">Your AI-powered resume review results</p>
              </div>
            </div>
            
            {/* Summary */}
            <div className="mb-6">
              <p className="text-zinc-300 leading-relaxed">{feedback.summary}</p>
            </div>
            
            {/* Recommendations */}
            {feedback.recommendations?.length > 0 && (
              <div className="mt-6 pt-6 border-t border-zinc-700/50">
                <div className="flex items-center gap-2 mb-4">
                  <FaRegLightbulb className="w-5 h-5 text-amber-400" />
                  <h4 className="text-lg font-semibold text-white">Key Recommendations</h4>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {feedback.recommendations.slice(0, 4).map((rec, index) => (
                    <div 
                      key={index}
                      className="flex items-start gap-2 p-3 rounded-lg bg-zinc-800/30 border border-zinc-700/30 hover:border-emerald-500/30 hover:bg-emerald-500/5 transition-all group"
                    >
                      <div className="w-6 h-6 rounded-full bg-linear-to-r from-emerald-500 to-teal-500 flex items-center justify-center text-white text-xs font-bold mt-0.5 group-hover:scale-110 transition-transform">
                        {index + 1}
                      </div>
                      <span className="text-zinc-300 group-hover:text-white transition-colors text-sm">{rec}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
          
          {/* Score */}
          <div className="shrink-0">
            <div className="relative">
              <ScoreCircle score={feedback.score} />
              <div className="text-center mt-6">
                <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-linear-to-r from-emerald-500/10 to-teal-500/10 border border-emerald-500/20">
                  <FiTrendingUp className="w-4 h-4 text-emerald-400" />
                  <span className="text-sm font-medium text-emerald-300">Overall Score</span>
                </div>
                <p className="text-sm text-zinc-400 mt-3 max-w-50">
                  Based on ATS compatibility, content quality, and relevance
                </p>
              </div>
            </div>
          </div>
        </div>
      </motion.div>

      {/* Action Buttons */}
      <motion.div 
        className="flex flex-wrap gap-4 justify-center mb-12"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.2 }}
      >
        <button
          onClick={onNewReview}
          className="group relative px-6 py-3 rounded-xl font-semibold bg-linear-to-r from-emerald-500 to-teal-500 text-white hover:shadow-2xl hover:shadow-emerald-500/30 transition-all duration-300 hover:-translate-y-1"
        >
          <div className="absolute inset-0 bg-linear-to-r from-emerald-600 to-teal-600 rounded-xl blur opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
          <span className="relative flex items-center gap-3">
            <FiRefreshCw className="w-5 h-5 group-hover:rotate-180 transition-transform duration-500" />
            Analyze Another Resume
          </span>
        </button>
        
        <button
          onClick={downloadReport}
          className="group px-6 py-3 rounded-xl font-semibold bg-zinc-800/40 backdrop-blur-sm border border-zinc-700/50 text-white hover:border-emerald-500/30 hover:bg-emerald-500/10 transition-all duration-300"
        >
          <span className="flex items-center gap-3">
            <FiDownload className="w-5 h-5 group-hover:animate-bounce" />
            Download Report
          </span>
        </button>
      </motion.div>

      {/* Analysis Sections */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-12">
        {sections.map((section, index) => (
          <motion.div
            key={section.id}
            initial={{ y: 20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ delay: index * 0.1 }}
            className="group"
          >
            <div className="glass-card p-6 h-full hover:border-emerald-500/30 hover:shadow-xl hover:shadow-emerald-500/10 transition-all duration-300 hover:-translate-y-1">
              {/* Section Header */}
              <div className={`inline-flex items-center gap-2 px-3 py-1.5 rounded-lg border mb-4 ${getColorClasses(section.color)} group-hover:scale-105 transition-transform`}>
                <section.icon className="w-4 h-4" />
                <span className="text-sm font-medium">{section.title}</span>
              </div>
              
              {/* Content */}
              {section.isList ? (
                <ul className="space-y-3">
                  {Array.isArray(section.content) && section.content.map((item, idx) => (
                    <motion.li 
                      key={idx} 
                      className="flex items-start gap-3 group/item hover:translate-x-1 transition-transform duration-300"
                      initial={{ opacity: 0, x: -10 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: index * 0.1 + idx * 0.05 }}
                    >
                      <div className={`w-2 h-2 rounded-full mt-2 shrink-0 ${getDotColor(section.color)} group-hover/item:scale-150 group-hover/item:animate-pulse transition-all`}></div>
                      <span className="text-zinc-300 group-hover/item:text-white transition-colors text-sm">{item}</span>
                    </motion.li>
                  ))}
                </ul>
              ) : (
                <p className="text-zinc-300 leading-relaxed text-sm group-hover:text-zinc-200 transition-colors">{section.content}</p>
              )}
            </div>
          </motion.div>
        ))}
      </div>

      {/* Final Score Card */}
      <motion.div 
        className="glass-card p-8 border border-emerald-500/20 bg-linear-to-r from-emerald-500/5 to-teal-500/5 hover:border-emerald-500/40 hover:shadow-2xl hover:shadow-emerald-500/20 transition-all duration-500"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.8 }}
      >
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className="p-3 rounded-xl bg-linear-to-r from-emerald-500 to-teal-500">
              <FiAward className="w-8 h-8 text-white" />
            </div>
            <div>
              <h3 className="text-xl font-bold text-white">Resume Score: {feedback.score}/100</h3>
              <p className="text-zinc-400 mt-1">
                {feedback.score >= 80 ? 'Excellent! Your resume is highly optimized.' :
                 feedback.score >= 60 ? 'Good! Some improvements can boost your score.' :
                 'Needs work. Follow the recommendations above to improve.'}
              </p>
            </div>
          </div>
          
          <div className="hidden md:block">
            <div className="flex items-center gap-2 text-sm text-emerald-400">
              <div className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse"></div>
              <span>AI-Powered Analysis</span>
            </div>
          </div>
        </div>
      </motion.div>
    </div>
  )
}

export default ResultsDisplay